FROM apache/airflow:2.9.1

# Dépendances (si tu as un requirements.txt)
COPY requirements.txt /requirements.txt
RUN python -m pip install --no-cache-dir -r /requirements.txt

# Bake des DAGs (tu l’as déjà)
COPY dags/ /opt/airflow/dags/

# ➜ Bake de la clé SA (DEV uniquement)
COPY keys/gcp-sa.json /opt/airflow/keys/gcp-sa.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/keys/gcp-sa.json
